# Murano Product Spec File - Smart Lighbulb Example Application


dataports:
-   alias: temperature
    format: float
-   alias: humidity
    format: float
-   alias: state
    format: integer
    initial: 0
-   alias: uptime
    format: integer
